fullnameOverride: idwall-test-stage

replicaCount: 2

image:
  repository: "idwall-test"
  tag: "stage"
  pullPolicy: Never

imagePullSecrets: []

rbac:
  create: false
  rules: []

podAnnotations: {}
podLabels: {}

service:
  type: NodePort
  port: 80
  targetPort: 3000
  annotations: {}

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  - name: NAME
    value: "Matheus Caselani"
envFrom:
  configMap: ""
  secret: ""

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}

containerPort: 3000
